# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

viterbi_fs_err <- function(rf, ep, nInd, nSnps, ref, alt, OPGP) {
    .Call('_GUSMap_viterbi_fs_err', PACKAGE = 'GUSMap', rf, ep, nInd, nSnps, ref, alt, OPGP)
}

